fix(mdeModel): use ChildProcess instead of execFileSync
Fixes compilation failure after merge:

    src/mde/mdeModel.ts(356,24): error TS2339: Property 'match' does not exist on type 'Buffer'.