refactor(fetcher): migrate withRetries to waitUntil (#6429)
## Problem
Recently a
[PR](https://github.com/aws/aws-toolkit-vscode/pull/6387/files#diff-c0100187095b7c009b33063c21a517248290b37d02ef10e9370d28cd3ed5d1ea)
on master combined `waitUntil` with `withRetries`. Once master merged
into feature branch, it caused this case to start erroring.

Leading to the following:
```
npm error src/shared/resourcefetcher/httpResourceFetcher.ts(164,16): error TS2304: Cannot find name 'withRetries'.
```

## Solution
- migrate to `waitUntil` in the same fashion as the PR. 

---

- Treat all work as PUBLIC. Private `feature/x` branches will not be
squash-merged at release time.
- Your code changes must meet the guidelines in
[CONTRIBUTING.md](https://github.com/aws/aws-toolkit-vscode/blob/master/CONTRIBUTING.md#guidelines).
- License: I confirm that my contribution is made under the terms of the
Apache 2.0 license.