package: increase minimum vscode to 1.68
Since #3328 5439f9527224d8d1c0b98cd9941ee55a0cefb9ae , CI job
"Integration Tests - minimum" fails (timeout) of some (not all) "invokes
and attaches" tests:

      5 failing
      1) SAM Integration Tests
           SAM runtime: python 3.10 (ZIP)
             Starting with a newly created python 3.10 (ZIP) SAM Application...
               target=api: invokes and attaches on debug request (F5):
         Error: Test length exceeded max duration: 300 seconds
      2) SAM Integration Tests
           SAM runtime: python 3.10 (ZIP)
             Starting with a newly created python 3.10 (ZIP) SAM Application...
               target=template: invokes and attaches on debug request (F5):
         Error: Test length exceeded max duration: 300 seconds
      3) SAM Integration Tests
           SAM runtime: go1.x (ZIP)
             Starting with a newly created go1.x (ZIP) SAM Application...
               target=template: invokes and attaches on debug request (F5):
         Error: Test length exceeded max duration: 300 seconds
      4) SAM Integration Tests
           SAM runtime: python 3.10 (ZIP)
             Starting with a newly created python 3.10 (ZIP) SAM Application...
               target=template: invokes and attaches on debug request (F5):
         Error: Test length exceeded max duration: 300 seconds
      5) SAM Integration Tests
           SAM runtime: go1.x (Image)
             Starting with a newly created go1.x (Image) SAM Application...
               target=template: invokes and attaches on debug request (F5):
         Error: Test length exceeded max duration: 300 seconds

Solution:
- Increase vscode minimum version to 1.68 (current Cloud9).
- Skip test in "templateRegistry.test.ts". See 8faa551f8a3c200e9190bd55d2d589de9eff3df1 #2622