fix(ci): "deadsnakes" causes unreliable CI
Problem:
deadsnakes sometimes fails our CI:

    lazr.restfulclient.errors.ServerError: HTTP Error 504: Gateway Time-out

Solution:
Remove use of deadsnakes. We no longer test against python 3.7/3.8.
Use python virtualenv and activate it with non-root `codebuild-user`.