refactor(shared): replace archiver with `@zip.js/zip.js` #4769
## Problem
The `archiver` package uses `fs` which is not available in the browser.
Running `npm run testWeb` results in the following error:

    TypeError: Cannot read properties of undefined (reading 'native')

## Solution
- Replace `archiver` with
[`@zip.js/zip.js`](https://gildas-lormeau.github.io/zip.js/) which has
browser support.