localLambdaRunner.test.ts: avoid ExtensionDisposableFiles.initialize()
Use FakeExtensionContext.getNew() instead, which forces
re-initialization of ExtensionDisposableFiles and avoids an exception if
it was already initialized.

ref: https://github.com/aws/aws-toolkit-vscode/pull/1097/files#r435476880

Other tests may call ExtensionDisposableFiles.initialize(), which
causes an error (all tests run in the same process):

    Error: ExtensionDisposableFiles already initialized
        at Function.<anonymous> (dist/src/shared/utilities/disposableFiles.js:9:4556)
        at Generator.next (<anonymous>)
        at /codebuild/output/src753373494/src/github.com/aws/aws-toolkit-vscode/dist/src/shared/utilities/disposableFiles.js:9:1746
        at new Promise (<anonymous>)
        at __awaiter (dist/src/shared/utilities/disposableFiles.js:9:662)
        at Function.initialize (dist/src/shared/utilities/disposableFiles.js:9:4311)
        at /codebuild/output/src753373494/src/github.com/aws/aws-toolkit-vscode/src/test/shared/codelens/localLambdaRunner.test.ts:23:40
        at Generator.next (<anonymous>)
        at /codebuild/output/src753373494/src/github.com/aws/aws-toolkit-vscode/dist/src/test/shared/codelens/localLambdaRunner.test.js:12:71
        at new Promise (<anonymous>)
        at __awaiter (dist/src/test/shared/codelens/localLambdaRunner.test.js:8:12)
        at Context.<anonymous> (src/test/shared/codelens/localLambdaRunner.test.ts:22:23)
        at processImmediate (internal/timers.js:439:21)
        at process.topLevelDomainCallback (domain.js:131:23)