tests: bump codecatalyst e2e skip
The tests are still being throttled, so bump the date.

    1) Test how this codebase uses the CodeCatalyst API
         Dev Environment functionality
           "before all" hook for "creates an empty Dev Environment":
       ThrottlingException: The request was denied due to request throttling.