CI: update node 10 => 12
yargs requires node 12 now:

    /codebuild/output/src266610087/src/github.com/aws/aws-toolkit-vscode/node_modules/yargs/build/index.cjs:1
    Error: yargs supports a minimum Node.js version of 12. Read our version support policy: https://github.com/yargs/yargs#supported-nodejs-versions