SAM: define "aws.samcli.location" config as "machine" scope
We can define a config value as "machine" scope.  But note the lack of
`vscode.ConfigurationTarget.Machine` scope, it is expected that we use
`vscode.ConfigurationTarget.Global`.  Then VSCode will resolve the
config value depending on "User" and "Remote" settings, and depending on
whether the current session is a Local or Remote instance.

NOTE:

- Current behavior of `scope=machine` is such that VSCode expects the
  user to enter a value: writeSetting() does not update the
  machine-local config.
- `scope=machine` has a known bug (issue is closed but NOT resolved):
  https://github.com/microsoft/vscode/issues/102543
- Long-term solution is to use a passive warning combined with
  just-in-time detection, rather than fighting VSCode (and the user) to
  auto-update a user setting. if the user config value is invalid:
  https://github.com/aws/aws-toolkit-vscode/pull/1242

REFERENCE:

For reference, `Workspace` and `WorkspaceFolder` scopes require
a workspace{folder} to write a setting, else writeSetting() fails:

    await this._configuration.writeSetting(k, detectedLocation, vscode.ConfigurationTarget.Workspace)

         2020-08-15 01:50:45 [ERROR]: failed to set config: 'samcli.location'='/home/linuxbrew/.linuxbrew/bin/sam',
         error: Error: Unable to write aws.samcli.location to Workspace Settings. This setting can be written only into User settings.
             at D.reject (file:///…/vs/workbench/workbench.desktop.main.js:5544:245)
             at D.resolveAndValidate (file:///…/vs/workbench/workbench.desktop.main.js:5547:622)
             at D.doWriteConfiguration (file:///…/vs/workbench/workbench.desktop.main.js:5541:414)
             at Object.factory (file:///…/vs/workbench/workbench.desktop.main.js:5541:190)
             at u.consume (file:///…/vs/workbench/workbench.desktop.main.js:130:421)
             at file:///…/vs/workbench/workbench.desktop.main.js:130:236
             at new Promise (<anonymous>)
             at u.queue (file:///…/vs/workbench/workbench.desktop.main.js:130:160)
             at D.writeConfiguration (file:///…/vs/workbench/workbench.desktop.main.js:5541:175)
             at C.writeConfigurationValue (file:///…/vs/workbench/workbench.desktop.main.js:5569:356)
             at file:///…/vs/workbench/workbench.desktop.main.js:5557:594
             at processTicksAndRejections (internal/process/task_queues.js:85:5) {
           name: 'Error',
           message: 'Unable to write aws.samcli.location to Workspace ' +
             'Settings. This setting can be written only into User ' +
             'settings.'
         }

    await this._configuration.writeSetting(k, detectedLocation, vscode.ConfigurationTarget.WorkspaceFolder)

         2020-08-15 01:50:45 [ERROR]: failed to set config: 'samcli.location'='/home/linuxbrew/.linuxbrew/bin/sam',
         error: Error: Unable to write to Folder Settings because no resource is provided.
             at D.reject (file:///…/vs/workbench/workbench.desktop.main.js:5544:245)
             at D.resolveAndValidate (file:///…/vs/workbench/workbench.desktop.main.js:5547:673)
             at D.doWriteConfiguration (file:///…/vs/workbench/workbench.desktop.main.js:5541:414)
             at Object.factory (file:///…/vs/workbench/workbench.desktop.main.js:5541:190)
             at u.consume (file:///…/vs/workbench/workbench.desktop.main.js:130:421)
             at file:///…/vs/workbench/workbench.desktop.main.js:130:236
             at new Promise (<anonymous>)
             at u.queue (file:///…/vs/workbench/workbench.desktop.main.js:130:160)
             at D.writeConfiguration (file:///…/vs/workbench/workbench.desktop.main.js:5541:175)
             at C.writeConfigurationValue (file:///…/vs/workbench/workbench.desktop.main.js:5569:356)
             at file:///…/vs/workbench/workbench.desktop.main.js:5557:594
             at processTicksAndRejections (internal/process/task_queues.js:85:5) {
           name: 'Error',
           message: 'Unable to write to Folder Settings because no resource is provided.'
         }