fix(tests): undefined "context" global #4626
Problem:
CI sometimes fails because the `ToolkitGlobals.context` global is undefined.

    TypeError: Cannot read properties of undefined (reading 'asAbsolutePath')
        at resolveIconId (…/aws-toolkit-vscode/packages/core/src/shared/icons.ts:90:33)
        at …/aws-toolkit-vscode/packages/core/src/shared/utilities/functionUtils.ts:77:64
        at createFeedbackNode (…/aws-toolkit-vscode/packages/core/src/codewhisperer/ui/codeWhispererNodes.ts:223:26)
        at Suite.<anonymous> (…/aws-toolkit-vscode/packages/core/src/test/codewhisperer/commands/basicCommands.test.ts:302:49)
        ...
        at runTests (…/aws-toolkit-vscode/packages/core/src/test/testRunner.ts:118:11)

Solution:
- Avoid calling non-trivial functions in `describe()` scope.
- During startup, proxy globals to give a more useful error.