TelemetryService: avoid timer race after shutdown() #1247
_timer may be undefined if shutdown() was called, despite
clearTimeout(), because the `async` closure scheduled by the previous
timer tick may be pending on the event-loop.

    TypeError: Cannot read property 'refresh' of undefined
        at DefaultTelemetryService.<anonymous> (/Volumes/workplace/aws-toolkit-vscode/src/shared/telemetry/defaultTelemetryService.ts:150:30)
        at Generator.next (<anonymous>)
        at fulfilled (/Volumes/workplace/aws-toolkit-vscode/dist/src/shared/telemetry/defaultTelemetryService.js:9:58)
        {stack: 'TypeError: Cannot read property 'refresh' of …ed/telemetry/defaultTelemetryService.js:9:58)', message: 'Cannot read property 'refresh' of undefined'}