Amazon Q Transform: Provide IDE bundled MavenRunner for transform  (#4070)
* added the addParentsPom to the maven command

* added the changelog

* Updated the change log message to be shorter per request.

* Updated the chnage log to include amazon q transform

* testing for updated mavne command

* temp mvnrunner

* format

* show transformation hub once the mvnrunner finished

* remove the showtransformationhub to the finally

* add telemetry

* todo:unit test

* a mavenrunner bug

* fix format

* add exception for mavenrunner

* change to catch throwable

* add a unit test

* slove the tread leak in unit test

* resume the .idea

* resume the .idea

* add the feature log

* resume to throw the exception when mvn

* revise the mavne failure notification message

* change the java class to kotlin & catch the NoClassDefFoundError exception

* fix the format

* fix detektMain

* Update .changes/next-release/feature-94919c2c-0d33-4f58-9c8e-f5b8cb661d1f.json

Co-authored-by: Richard Li <742829+rli@users.noreply.github.com>

* Update jetbrains-core/src/software/aws/toolkits/jetbrains/services/codemodernizer/ideMaven/TransformMavenRunner.kt

Co-authored-by: Richard Li <742829+rli@users.noreply.github.com>

* Apply suggestions from code review

Co-authored-by: Richard Li <742829+rli@users.noreply.github.com>

* dedupe the commands

* remove unnecessary ?

---------

Co-authored-by: Parsa Jorat <parsjora@amazon.com>
Co-authored-by: joratp <64931968+joratp@users.noreply.github.com>
Co-authored-by: Xi Shen <xis@amazon.com>
Co-authored-by: Richard Li <742829+rli@users.noreply.github.com>