Consolas: Merge all features into feature/vector (#464)
* feat: integrate cognito idp with consolas

* fix: address pr feedback

* [Consolas][High] Consolas Security Scan UX for VSC and C9 (#402)

* Consolas security scan feature for VSC and C9

* Merge security scan nodes

* Update panel and commands titles

* Make re-scan for VSC in one line

* Extract activation of security scan into a function

* Webviewview panel & view title changes

* Adjust validation range in panel

* Address comments

* Use Command URI

* fix: update file name and identity pool ids

* chore: update consolas api model

* Swith to use @types/codicons (#414)

* feat: add consolas token input

* [Consolas][High] Add context truncation which uses dependency graph algorithm for java and python (#415)

* Consolas security scan feature for VSC and C9

* Merge security scan nodes

* Update panel and commands titles

* Make re-scan for VSC in one line

* Extract activation of security scan into a function

* Webviewview panel & view title changes

* Dependency graphs working solution

* Fixed working solution with java edge cases

* Integrate with StartScan command

* Clean code base and remove useless

* [Consolas][High] Consolas Security Scan UX for VSC and C9 (#402)

* Consolas security scan feature for VSC and C9

* Merge security scan nodes

* Update panel and commands titles

* Make re-scan for VSC in one line

* Extract activation of security scan into a function

* Webviewview panel & view title changes

* Adjust validation range in panel

* Address comments

* Use Command URI

* Swith to use @types/codicons

* Use vscode.Uri.file

* Use path.join

* Reduce property number

* Factory pattern for dependency graph

* Abstract some methods and the parent class

* Set timeout for context truncation

* feat: update UX for consolas token input

* fix: address pr feedback

* fix: throw if access token is undefined

* refactor: accountless commands and nodes

* [Consolas][High] Follow up updates for PR-415 (#423)

* Address additional comments from PR-415

* Handle import static ...

* Simplify raw path jon statement

* Consolas Pagination

* Paginated fully working with automatic trigger

* Fix old test cases

* Add pagination for manual trigger

* Add status bar Item for Consolas for pagination

* Exit scenerios for pagination

* ChangeRecommendationname&Exitstatefix

* NextResponsetestcase

* feat: add access token to request header

* fix: invalidate the access token on validation error

* Statusbarfix

* Minor bug fixes

* Updated inline to singleton class and fixed test cases

* resolveconflicts

* remove global var telemetry context

* fix: hide accountless for cloud9

* Bug: status bar not visible after VsCode restart

* update

* fix bug in test cases

* add package-lock.json change

* remove inline completion global variable

* Add Prod endpoint back to consolas

* [Consolas][High] CodeScan E2E working solution (with dev endpoint) (#431)

* Address additional comments from PR-415

* Handle import static ...

* Simplify raw path jon statement

* E2E working solution plus down-to file level truncation for Java

* Address comments

* Updated sdk model

* Use pageableToCollection for listing

* Refactor based on comments

* add hack for access token

* fix bug

* Bug fixing and one way navigation

* Testcasefix

* Update consolas client

* fix bugs

* remove unnecessary func

* update service-2

* Missingheaderconsolas.ts

* fix weird code

alpha  build

refactor

debugging typeahead

debug misc UI bug; typeahead

no concurrent auto t

fix typeahead bug

fix test cases

fix max result bug

remove max Result for ListReco

Merge code scan command to basicCommands

fix OT webview display empty reco bug

gamma endpoint

fix cfg bug

fix bug of cursor position after format

clean up

in fixing unit tests

fix unit test

update alpha/gamma endpoint

no CG in C9

prod endpoint

fix(util): update AsyncCollection with better types #2657

fix(stepFunctions): bump amazon-states-language-service dependency to ^1.7.2 (#2660)

* Bump amazon-states-language-service dependency to ^1.7.2
* Add changelog entry
fix(git): prevent users from passing additional flags to ls-remote (#2661)

before:
error: unknown option `test'

after:
fatal: strange pathname '--test' blocked
fix(cdk): address more C9 edge-cases #2662

feat(runtimes): nodejs16.x #2628

Merge branch 'feature/vector' into autoMerge/feature/vector
Merge pull request #461 from aws/autoMerge/feature/vector

Merge staging into feature/vector
Merge branch 'feature/vector' into pentesting_fixes
try fix unit test bug in cloud

Merge branch 'pentesting_fixes' of github.com:leigaol/aws-toolkit-vscode-staging into pentesting_fixes

fix perf not found bug in unit test

feat: add optout support

fix: add resume icon

add performance in recHandler

resolve conflict

fix: fix input value when re-enter

Fix standalone python file use case

fix(performance): Explicitly include items in the vsix #2669

closes #1899
Merge staging into feature/vector

Merge branch 'feature/vector' into pentesting_fixes
Skip build/ symbolic link for python project

Telemetry pagination (#4)

* Adding Pagination Telemetry changes

* pagination SuggestionIndex change

* Paginationprogress change
fix weird code

alpha  build

no concurrent auto t

fix typeahead bug

fix test cases

fix max result bug

remove max Result for ListReco

Merge code scan command to basicCommands

fix OT webview display empty reco bug

update alpha/gamma endpoint

no CG in C9

fix(util): update AsyncCollection with better types #2657

fix(stepFunctions): bump amazon-states-language-service dependency to ^1.7.2 (#2660)

* Bump amazon-states-language-service dependency to ^1.7.2
* Add changelog entry
fix(git): prevent users from passing additional flags to ls-remote (#2661)

before:
error: unknown option `test'

after:
fatal: strange pathname '--test' blocked
fix(cdk): address more C9 edge-cases #2662

feat(runtimes): nodejs16.x #2628

Merge branch 'feature/vector' into autoMerge/feature/vector
Merge pull request #461 from aws/autoMerge/feature/vector

Merge staging into feature/vector
prod endpoint

Merge branch 'feature/vector' into pentesting_fixes
try fix unit test bug in cloud

Merge branch 'pentesting_fixes' of github.com:leigaol/aws-toolkit-vscode-staging into pentesting_fixes

fix perf not found bug in unit test

fix: add resume icon

add performance in recHandler

resolve conflict

fix: fix input value when re-enter

Fix standalone python file use case

fix(performance): Explicitly include items in the vsix #2669

closes #1899
Merge staging into feature/vector

Merge branch 'feature/vector' into pentesting_fixes
Skip build/ symbolic link for python project

Telemetry pagination (#4)

* Adding Pagination Telemetry changes

* pagination SuggestionIndex change

* Paginationprogress change

Merge branch 'feature/vector' into pentesting_fixes
Remvoe security scan panel from C9

Merge branch 'pentesting_fixes' of https://github.com/leigaol/aws-toolkit-vscode-staging into pentesting_fixes

BugFix: mark Accept undo/redo stack as false

Merge pull request #5 from leigaol/acceptRecomm_fix

BugFix: mark Accept undo/redo stack as false
Merge branch 'pentesting_fixes' into feat/optout
Merge pull request #6 from zixlin7/feat/optout

feat: add optout support
Merge branch 'pentesting_fixes' of https://github.com/leigaol/aws-toolkit-vscode-staging into pentesting_fixes

ConsolasTracker Exception fix

* maxReco=1 for C9

Co-authored-by: aws-toolkit-automation <43144436+aws-toolkit-automation@users.noreply.github.com>
Co-authored-by: Zoe Lin <zoelin@amazon.com>
Co-authored-by: Wade Fang <90796612+fangwade007@users.noreply.github.com>
Co-authored-by: Zoe Lin <60411978+zixlin7@users.noreply.github.com>
Co-authored-by: Prateek Chauhan <prateekchauhan091@gmail.com>
Co-authored-by: Meghana Gunuganti <gmeghrao@amazon.com>
Co-authored-by: gmeghrao <92111456+gmeghrao@users.noreply.github.com>
Co-authored-by: Prateek Chauhan <48580344+prateekch91@users.noreply.github.com>