stepFunctions visualization: do not fail if directory exists
`updateCache()` uses `Promise.all()` to call multiple tasks in parallel
which eventually call `writeToLocalStorage()`, targeting the same
directory.

fixes https://github.com/aws/aws-toolkit-vscode/issues/1230

Error observed in CI:

    2020-08-06 21:54:27 [DEBUG]: Folder for graphing script and styling doesnt exist. Creating it.
        1) opens up a webview when there is an active text editor
    2020-08-06 21:54:27 [ERROR]: [Error: EEXIST: file already exists, mkdir '/root/.config/Code - Insiders/User/globalStorage/amazonwebservices.aws-toolkit-vscode/visualization'] {
      errno: -17,
      code: 'EEXIST',
      syscall: 'mkdir',
      path: '/root/.config/Code - Insiders/User/globalStorage/amazonwebservices.aws-toolkit-vscode/visualization'
    }
    2020-08-06 21:54:27 [ERROR]: Failed to update State Machine Graph css assets
    2020-08-06 21:54:27 [ERROR]: [Error: EEXIST: file already exists, mkdir '/root/.config/Code - Insiders/User/globalStorage/amazonwebservices.aws-toolkit-vscode/visualization'] {
      errno: -17,
      code: 'EEXIST',
      syscall: 'mkdir',
      path: '/root/.config/Code - Insiders/User/globalStorage/amazonwebservices.aws-toolkit-vscode/visualization'
    }
    2020-08-06 21:54:27 [DEBUG]: Unable to setup webview panel.
    2020-08-06 21:54:27 [ERROR]: [Error: EEXIST: file already exists, mkdir '/root/.config/Code - Insiders/User/globalStorage/amazonwebservices.aws-toolkit-vscode/visualization'] {
      errno: -17,
      code: 'EEXIST',
      syscall: 'mkdir',
      path: '/root/.config/Code - Insiders/User/globalStorage/amazonwebservices.aws-toolkit-vscode/visualization'
    }
    2020-08-06 21:54:27 [VERBOSE]: Step Functions is getting content from https://do0of8uwbahzz.cloudfront.net/graph-0.1.5.css
    2020-08-06 21:54:27 [VERBOSE]: Step Functions finished getting content from https://do0of8uwbahzz.cloudfront.net/graph-0.1.5.css
        ✓ correctly displays content when given a sample state machine (312ms)
    2020-08-06 21:54:27 [DEBUG]: Sending update message to webview.
    2020-08-06 21:54:27 [DEBUG]: Successfully updated state machine graph.
        ✓ correctly displays content when given a sample state machine in yaml (219ms)
    2020-08-06 21:54:27 [DEBUG]: Sending update message to webview.
        ✓ update webview is triggered when user saves correct text editor (101ms)
    2020-08-06 21:54:27 [DEBUG]: Sending update message to webview.
        ✓ throws an error if no active text editor is open
    2020-08-06 21:54:27 [ERROR]: Could not get active text editor for state machine render.
    2020-08-06 21:54:27 [DEBUG]: Sending update message to webview.
        ✓ doesnt update the graph if a seperate file is opened or modified (268ms)
      VSCode tests
    activateExtension request: amazonwebservices.aws-toolkit-vscode
    ...
    activateExtension request: amazonwebservices.aws-toolkit-vscode
    Extension is already active
        ✓ activates the extension
      46 passing (31s)
      12 pending
      1 failing
      1) visualizeStateMachine
           opens up a webview when there is an active text editor:
         AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
      assert.ok(result)
          at /codebuild/output/src459603120/src/github.com/aws/aws-toolkit-vscode/src/integrationTest/stepFunctions/visualizeStateMachine.test.ts:129:16
          at Generator.next (<anonymous>)
          at fulfilled (dist/src/integrationTest/stepFunctions/visualizeStateMachine.test.js:9:58)
    Error: 1 tests failed.
    Error: 1 tests failed.
    Exit code:   1