fix(tests): undefined "context" global
Problem:
CI sometimes fails because the `ToolkitGlobals.context` global is undefined.
This suggests either:
- `globalSetup.test.ts` is not invoked before the test is executed
- mocha initalize `describe()` scope, before executing any tests (which _includes_ `globalSetup.test.ts`)?

    TypeError: Cannot read properties of undefined (reading 'asAbsolutePath')
        at resolveIconId (…/aws-toolkit-vscode/packages/core/src/shared/icons.ts:90:33)
        at …/aws-toolkit-vscode/packages/core/src/shared/utilities/functionUtils.ts:77:64
        at createFeedbackNode (…/aws-toolkit-vscode/packages/core/src/codewhisperer/ui/codeWhispererNodes.ts:223:26)
        at Suite.<anonymous> (…/aws-toolkit-vscode/packages/core/src/test/codewhisperer/commands/basicCommands.test.ts:302:49)
        at Object.create (…/aws-toolkit-vscode/node_modules/mocha/lib/interfaces/common.js:148:19)
        at context.describe.context.context (…/aws-toolkit-vscode/node_modules/mocha/lib/interfaces/bdd.js:42:27)
        at Suite.<anonymous> (…/aws-toolkit-vscode/packages/core/src/test/codewhisperer/commands/basicCommands.test.ts:301:5)
        at Object.create (…/aws-toolkit-vscode/node_modules/mocha/lib/interfaces/common.js:148:19)
        at context.describe.context.context (…/aws-toolkit-vscode/node_modules/mocha/lib/interfaces/bdd.js:42:27)
        at Object.<anonymous> (…/aws-toolkit-vscode/packages/core/src/test/codewhisperer/commands/basicCommands.test.ts:56:1)
        at Module._compile (node:internal/modules/cjs/loader:1163:14)
        ...
        at require (node:internal/modules/cjs/helpers:102:18)
        at …/aws-toolkit-vscode/node_modules/mocha/lib/mocha.js:414:36
        at Array.forEach (<anonymous>)
        at Mocha.loadFiles (…/aws-toolkit-vscode/node_modules/mocha/lib/mocha.js:411:14)
        at Mocha.run (…/aws-toolkit-vscode/node_modules/mocha/lib/mocha.js:969:10)
        at …/aws-toolkit-vscode/packages/core/src/test/testRunner.ts:94:19
        at new Promise (<anonymous>)
        at runMocha (…/aws-toolkit-vscode/packages/core/src/test/testRunner.ts:93:16)
        at runTests (…/aws-toolkit-vscode/packages/core/src/test/testRunner.ts:118:11)

Solution:
- During startup, proxy globals to give a more useful error.
- Avoid calling non-trivial functions in `describe()` scope.