SAM debug: detect & surface "low disk space" #171
If `sam build` fills up the disk while building a Docker image
(--use-container) it may fail with this message:
    RuntimeError: Container does not exist