telemetry: add result field to metric #4171
      1) transformByQ
           "before all" hook for "WHEN upload payload with missing sha256 in headers THEN fails to upload":
         Error: Metric `codeTransform_jobCreateZipEndTime` was emitted without the `result` property. This property is always required. Consider using `.run()` instead of `.emit()`, which will set these properties automatically. See https://github.com/aws/aws-toolkit-vscode/blob/master/docs/telemetry.md#guidelines