fix: integ CI fails with "TypeError: Cannot redefine property: window" #3784
Problem:
Since enabling "esModuleInterop" 08d1072e8253ab3a533f6507021d83f5b68b0657, integ
tests and e2e tests fail:

    rejected promise not handled within 1 second: TypeError: Cannot redefine property: window
    --
    680 | stack trace: TypeError: Cannot redefine property: window
    681 | at Function.defineProperty (<anonymous>)
    682 | at patchObjectDescriptor (/codebuild/output/src503097238/src/src/test/setupUtil.ts:115:12)
    683 | at patchObject (/codebuild/output/src503097238/src/src/test/setupUtil.ts:106:12)
    684 | at patchWindow (/codebuild/output/src503097238/src/src/testInteg/globalSetup.test.ts:59:30)
    685 | at Runner.<anonymous> (/codebuild/output/src503097238/src/src/testInteg/globalSetup.test.ts:33:5)
    686 | at Generator.next (<anonymous>)
    687 | at /codebuild/output/src503097238/src/dist/src/testInteg/globalSetup.test.js:35:71
    688 | at new Promise (<anonymous>)
    689 | at __awaiter (/codebuild/output/src503097238/src/dist/src/testInteg/globalSetup.test.js:31:12)
    690 | at Runner.mochaGlobalSetup (/codebuild/output/src503097238/src/dist/src/testInteg/globalSetup.test.js:54:12)
    691 | at Mocha._runGlobalFixtures (/codebuild/output/src503097238/src/node_modules/mocha/lib/mocha.js:1214:21)
    692 | at async Mocha.runGlobalSetup (/codebuild/output/src503097238/src/node_modules/mocha/lib/mocha.js:1174:5)
    693 | at async runAsync (/codebuild/output/src503097238/src/node_modules/mocha/lib/mocha.js:1016:11)
    694 | Cannot redefine property: window: TypeError: Cannot redefine property: window
    695 | at Function.defineProperty (<anonymous>)
    696 | at patchObjectDescriptor (/codebuild/output/src503097238/src/src/test/setupUtil.ts:115:12)
    697 | at patchObject (/codebuild/output/src503097238/src/src/test/setupUtil.ts:106:12)
    698 | at patchWindow (/codebuild/output/src503097238/src/src/testInteg/globalSetup.test.ts:59:30)
    699 | at Runner.<anonymous> (/codebuild/output/src503097238/src/src/testInteg/globalSetup.test.ts:33:5)
    700 | at Generator.next (<anonymous>)
    701 | at /codebuild/output/src503097238/src/dist/src/testInteg/globalSetup.test.js:35:71
    702 | at new Promise (<anonymous>)
    703 | at __awaiter (/codebuild/output/src503097238/src/dist/src/testInteg/globalSetup.test.js:31:12)
    704 | at Runner.mochaGlobalSetup (/codebuild/output/src503097238/src/dist/src/testInteg/globalSetup.test.js:54:12)
    705 | at Mocha._runGlobalFixtures (/codebuild/output/src503097238/src/node_modules/mocha/lib/mocha.js:1214:21)
    706 | at async Mocha.runGlobalSetup (/codebuild/output/src503097238/src/node_modules/mocha/lib/mocha.js:1174:5)
    707 | at async runAsync (/codebuild/output/src503097238/src/node_modules/mocha/lib/mocha.js:1016:11)
    708 | rejected promise not handled within 1 second: TypeError: Cannot read property 'registerContributor' of undefined
    709 | stack trace: TypeError: Cannot read property 'registerContributor' of undefined
    710 | at /codebuild/output/src503097238/src/src/shared/extensions/yaml.ts:46:21
    711 | at Generator.next (<anonymous>)
    712 | at fulfilled (/codebuild/output/src503097238/src/dist/src/shared/extensions/yaml.js:5:3451)
    713 | at runMicrotasks (<anonymous>)
    714 | at processTicksAndRejections (internal/process/task_queues.js:93:5)
    715 | Cannot read property 'registerContributor' of undefined: TypeError: Cannot read property 'registerContributor' of undefined
    716 | at /codebuild/output/src503097238/src/src/shared/extensions/yaml.ts:46:21
    717 | at Generator.next (<anonymous>)
    718 | at fulfilled (/codebuild/output/src503097238/src/dist/src/shared/extensions/yaml.js:5:3451)
    719 | at runMicrotasks (<anonymous>)
    720 | at processTicksAndRejections (internal/process/task_queues.js:93:5)

Solution:
Use a default import instead of a namespace import (import * as vscode from 'vscode').
when trying to patch the `window` object.

Signed-off-by: nkomonen <nkomonen@amazon.com>