fix(tests): "TypeError: … undefined (reading 'isMapped')" #4250
Problem:
Even after 6d66720b8782944376a99b35ab3c72f97d409415, tests still
sometimes fail because the global schemaService is not properly
restored:

    createNewSamApp
      addInitialLaunchConfiguration
        produces and returns initial launch configurations:
    TypeError: Cannot read properties of undefined (reading 'registerMapping')
     at CloudFormationTemplateRegistry.process (src/shared/fs/templateRegistry.ts:38:35)
     at async CloudFormationTemplateRegistry.addItem (src/shared/fs/watchedFiles.ts:214:26)
     at async Context.<anonymous> (src/test/lambda/commands/createNewSamApp.test.ts:118:13)
    ...
    rejected promise not handled within 1 second: TypeError: Cannot read properties of undefined (reading 'isMapped')
    stack trace: TypeError: Cannot read properties of undefined (reading 'isMapped')
        at /Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/src/shared/awsFiletypes.ts:69:59

Solution:
Use a spy on the actual service, instead of replacing the service with
a temporary stub.