fix(ci): skip CHANGELOG script for feature/standalone #4700
Problem:
"prerelease" and "package test" CI jobs are failing:

     error: changelog data file already exists: /codebuild/output/src1532600206/src/github.com/aws/aws-toolkit-vscode/.changes/2.19.0-SNAPSHOT.json

because 3890da4d0ef49c026731b97fe52b54fa70bbbe2a did a "fake release" on
`feature/standalone`, then later `public/master` merged-in
(1170aa9a1d27) more changelog entries (without bumping the version).

Solution:
- don't generate CHANGELOG for feature/standalone
- revert 3890da4d0ef49c026731b97fe52b54fa70bbbe2a (because 2.19 was not actually released yet)
- TODO: move `.changes/` to subprojects