build(deps-dev): bump typescript-eslint #2328
Needed in order to upgrade eslint.

> TypeError: Failed to load plugin '@typescript-eslint' declared in
> '--config': Class extends value undefined is not a constructor or null

https://github.com/eslint/eslint/issues/15149
Need to upgrade `@typescript-eslint/*` simultaneously?

Fix:
    src/webviews/server.ts
      43:5  error  Constraining the generic type `P` to `any` does nothing and is unnecessary @typescript-eslint/no-unnecessary-type-constraint