Merge staging into feature/vector-custom (#926)
* refactor: auth code (#3525)


    - The overall folder named is now src/auth/ instead of src/credentials/
    - The auth.ts module now focuses only on the Auth client and does not have other related code in the same module
    - When dealing with a Connection object like an Sso, BuilderId, or Credentials/IAM connection, related code was moved from auth.ts to connection.ts. This helps to avoid circular dependencies when working with connections + auth.
    - The functional code previously in auth.ts was moved to src/auth/utils.ts to create separation between the functions and the Auth client.
    - Existing credentials related files were moved in to src/auth/credentials/ to consolidate them
    - A new folder was made in src/auth/ui/ that will hold all auth related UI code, including the status bar item and add connection webview.


Signed-off-by: Nikolas Komonen <nkomonen@amazon.com>

* build: forceConsistentCasingInFileNames #3533

* build(deps-dev): bump vue-loader from 17.1.1 to 17.2.2 (#3531)

Bumps [vue-loader](https://github.com/vuejs/vue-loader) from 17.1.1 to 17.2.2.
- [Release notes](https://github.com/vuejs/vue-loader/releases)
- [Changelog](https://github.com/vuejs/vue-loader/blob/main/CHANGELOG.md)
- [Commits](https://github.com/vuejs/vue-loader/compare/v17.1.1...v17.2.2)

---
updated-dependencies:
- dependency-name: vue-loader
  dependency-type: direct:development
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* ci: skip vscode:prepublish #3536

Problem:
`vscode:prepublish` takes 2 minutes in each job, but this is
unnecessary. It's already tested by the `packageTestVsix.yml` CI job
(`npm run package`).

Solution:
Drop `vscode:prepublish` in all CI jobs except `packageTestVsix.yml`.

* build(deps): bump xml2js from 0.5.0 to 0.6.0 (#3542)

Bumps [xml2js](https://github.com/Leonidas-from-XIV/node-xml2js) from 0.5.0 to 0.6.0.
- [Commits](https://github.com/Leonidas-from-XIV/node-xml2js/compare/0.5.0...0.6.0)

---
updated-dependencies:
- dependency-name: xml2js
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Remove year from copyright header (#3544)

## Problem
The date in the license is unnecessary and noisy

## Solution
Apply `Copyright ([0-9]{4}[-,]{0,1}[ ]{0,1}){1,} Amazon.com, Inc` regex to all files, replacing with `Copyright Amazon.com, Inc`

* build: "npm run package -- --feature foo"

Problem:
The version string of feature-branch artifacts is not visually distinct
from master artifacts.

Solution:
If `--feature foo` is passed to `package.ts`, prepend the feature name
to the prerelease string. Example:

    $ npm run package -- --feature foo
    => 1.77.0-foo-1d4fafb53fec

* ci: publish prerelease on push to master, feature/x

Problem:
- Artifacts for `master` branch and `feature/x` branches are not
  published to a canonical location, which makes it difficult for
  scripts to consume them.
- Artifacts from `feature/x` branches are not advertised in GitHub's
  "release" UI.
- Per-commit artifacts expire after a few days.

Solution:
- Publish artifacts from `feature/x` branches to a fixed `pre-x` tag.
- Publish artifacts from `master` branch to a fixed `prerelease` tag.

* Refactor: test CollectionUtils -> general collectionUtils.  (#3535)

* (rebase): remove ec2 changes from this branch

* remove TODO comment

Co-authored-by: JadenSimon <31319484+JadenSimon@users.noreply.github.com>

* delete final remnants of ec2

* delete old file

---------

Co-authored-by: JadenSimon <31319484+JadenSimon@users.noreply.github.com>

* authWebview: Identity Center for CW (#3481)

* refactor: Consolidate sso validation code in to new file

This moves+updates existing sso validation code in
to its own module so that it can be reused elsewhere.

The new file created is `src/auth/sso/validation.ts`

Additionally, the existing code that uses this validation
is updated to use the new changes.

Signed-off-by: Nikolas Komonen <nkomonen@amazon.com>

* authWebview: IAM Identity Center form

- Can enter start url + region and it will
  attempt to use those to connect with code whisperer
- Validation of start url (format + already exists)

Signed-off-by: Nikolas Komonen <nkomonen@amazon.com>

---------

Signed-off-by: Nikolas Komonen <nkomonen@amazon.com>

* fix: lint test error message not printed (#3554)

fix: lint test error message get printed

Before the actual error message wasn't being
printed on failure

Signed-off-by: Nikolas Komonen <nkomonen@amazon.com>

* fix(sam): SAM CLI 1.85-1.86 fails on Windows #3559

Problem:
SAM CLI 1.85-1.86 fails on Windows.

Solution:
Attempt to detect the situation, and show a warning.
Also fix a typo in `locationPaths`.

* fix(ci): "Running as root without --no-sandbox"

* revert --no-sandbox

* ci: skip go tests

Problem:
Since switching to "unprivileged" environment to fix the "Running as
root without --no-sandbox" error #3551 (also because running as root
causes lots of other problems, e.g. "npm ci --unsafe-perm"), most integ
tests are working except SAM before hook:

    1 failing
    1) SAM Integration Tests
       "before all" hook in "SAM Integration Tests":
       Error: command 'go.tools.install' not found

Solution:
Skip the go tests temporarily.

* ci: run-as unprivileged user

Problem:
Running as root causes lots of warnings, latest (fatal) example (https://github.com/aws/aws-toolkit-vscode/issues/3550):
    [10429:0609/133041.674749:ERROR:network_service_instance_impl.cc(521)] Network service crashed, restarting service.
    19 | [0609/133041.694037:FATAL:electron_main_delegate.cc(304)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

Solution:
- Use "run-as" directive and "export $HOME".
- docker is already running, don't need "nohup /usr/local/bin/dockerd".
  Instead just give the user permissions to the socket: "chmod 666 /var/run/docker.sock"
- remove useless things:
  pylint
- TODO: "goenv", "go" are broken...

* docs: prerelease artifacts #3561

* ci: run-as unprivileged user #3564

ref f53186e443093db89dbf3d4d813915813e3404b6

* ci: run-as unprivileged user #3565

ref 59a0a83ca1902e7c4ae3036f0d04c3433050f6c8
ref f53186e443093db89dbf3d4d813915813e3404b6

* telemetry: aws_openUrl #3566

Capture metrics for generic URLs.

* feat(codewhisperer): roll out classifier to more languages #3546

* feat(codewhisperer): improve file context fetching logic #3567

Improve codewhisperer file context fetching logic for generating recommendations.

* Release 1.77.0

* Update version to snapshot version: 1.78.0-SNAPSHOT

* lint #3569

* ci: reduce codecov requirement to 70% #3562

Problem:
Each PR has failing CI because of a 75% code coverage requirement that.

Solution:
Reduce the requirement to 70%. We can increase to 75% if/when code
coverage is increased.

---------

Signed-off-by: Nikolas Komonen <nkomonen@amazon.com>
Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: Nikolas Komonen <118216176+nkomonen-amazon@users.noreply.github.com>
Co-authored-by: Justin M. Keyes <jmkeyes@amazon.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: JadenSimon <31319484+JadenSimon@users.noreply.github.com>
Co-authored-by: Hweinstock <42325418+Hweinstock@users.noreply.github.com>
Co-authored-by: Zoe Lin <60411978+zixlin7@users.noreply.github.com>
Co-authored-by: Will Lo <96078566+Will-ShaoHua@users.noreply.github.com>
Co-authored-by: aws-toolkit-automation <>
Co-authored-by: andrewyuq <89420755+andrewyuq@users.noreply.github.com>