fix(inline-completion): potential inline completion failure due to input validation exception of supplemental context (#6758)
## Problem
ERROR: `at 'supplementalContexts' failed to satisfy constraint: Member
must have length less than or equal to 5`

ERROR: `supplementalContexts.1.member.content' failed to satisfy
constraint: Member must have length less than or equal to 10240`

## Solution

Jebtrains PR https://github.com/aws/aws-toolkit-jetbrains/pull/5466

     * Requirement
     * - Maximum 5 supplemental context.
     * - Each chunk can't exceed 10240 characters
     * - Sum of all chunks can't exceed 20480 characters

---

- Treat all work as PUBLIC. Private `feature/x` branches will not be
squash-merged at release time.
- Your code changes must meet the guidelines in
[CONTRIBUTING.md](https://github.com/aws/aws-toolkit-vscode/blob/master/CONTRIBUTING.md#guidelines).
- License: I confirm that my contribution is made under the terms of the
Apache 2.0 license.