fix(ci): remove deprecated Python configs #3988
Problem:

  1) SAM Integration Tests
       "before all" hook in "SAM Integration Tests":
     CodeExpectedError: Unable to write to Workspace Settings because python.linting.pylintEnabled is not a registered configuration.

Solution:

Remove setting that was broken upstream.

integ logs from last successful integ CI on master is comparable to PR (both ~27k lines).