build: use TSESTree instead of "dist/generated/ast-spec"
Problem:
After updating to @typescript-eslint/parser 7.x, importing '@typescript-eslint/types/dist/generated/ast-spec' fails:

    lib/rules/no-await-on-vscode-msg.ts(15,34): error TS2307: Cannot find module '@typescript-eslint/types/dist/generated/ast-spec' or its corresponding type declarations.
    lib/rules/no-await-on-vscode-msg.ts(40,13): error TS2322: Type '"error"' is not assignable to type 'RuleRecommendation | RuleRecommendationAcrossConfigs<never[]> | undefined'.
    lib/rules/no-only-in-tests.ts(13,62): error TS2307: Cannot find module '@typescript-eslint/types/dist/generated/ast-spec' or its corresponding type declarations.
    lib/rules/no-only-in-tests.ts(32,13): error TS2322: Type '"error"' is not assignable to type 'RuleRecommendation | RuleRecommendationAcrossConfigs<never[]> | undefined'.
    lib/rules/no-only-in-tests.ts(60,25): error TS2322: Type '`${any}OnlyErrMsg`' is not assignable to type '"describeOnlyErrMsg" | "itOnlyErrMsg"'.

Solution:
Import from '@typescript-eslint/utils' instead.