tests: skip E2E tests
Problem:
e2e tests always fail because of throttling, and whatever this is:

    ProtocolError: Protocol error (Page.navigate): Target closed

Solution:
Skip the tests until these issues are fixed.