fix(test): intermittent failure in pickerPrompter.test.ts
Problem:
1. since f7c3dc0961c969d3b240eef8adf21ee116133a47 #2168 , seeing these CI failures:
   ```
   QuickPickPrompter
        can select an item:
      Uncaught TypeError: this.onSuccess is not a function
       at Timeout._onTimeout (.vscode-test/vscode-linux-x64-1.42.0/VSCode-linux-x64/resources/app/extensions/json-language-features/client/dist/jsonMain.js:9:106345)
   ...
   "after each" hook for "creates a new prompter when given an AsyncIterable":
      Uncaught TypeError: this.onSuccess is not a function
       at Timeout._onTimeout (.vscode-test/vscode-linux-x64-1.42.0/VSCode-linux-x64/resources/app/extensions/json-language-features/client/dist/jsonMain.js:9:106345)
   ```
2.

Solution:
1. ensure sinon.createSandbox() in beforeEach, restore() in afterEach()

related
- https://github.com/aws/aws-toolkit-vscode/issues/1281
- https://github.com/aws/aws-toolkit-vscode/issues/1233